name: Android

on: [push, pull_request]

jobs:        
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Android
      run: |
        nuget restore
        cd Zgadnij.Android
        msbuild Zgadnij.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
